### ISSUE TITLE
Issue with the TypeScript declaration for AutoHeightWebView

### ISSUE THREAD

**Issue by madandrija** [iou90/react-native-autoheight-webview#181] opened 2020-08-27 08:25 UTC
**Bug description:**

After updating to 1.5.3 from 1.5.2 (after the switch to `AutoHeightWebView extends WebView`), TS is showing me `JSX element type 'AutoHeightWebView' does not have any construct or call signatures`

**To Reproduce:**

Update to the latest version

**Expected behavior:**

Everything to work as expected

**Screenshots/Videos:**

![image](https://user-images.githubusercontent.com/44572935/91415239-0956d480-e84e-11ea-93e1-1a7d7961ff93.png)

**Environment:**
 - react-native version: 0.63.2
 - react-native-webview version: 10.8.2
 - react-native-autoheight-webview version: 1.5.3
 - typescript: 4.0.2,
 - @types/react: 16.9.48,
 - @types/react-native: 0.63.10,

**Comment by iou90** [comment] 2020-09-01 07:38
Should be fixed from v1.5.4.

**Comment by madandrija** [comment] 2020-10-15 15:07
Fixed, thanks!

**Comment by abenoit-reeliant** [comment] 2020-12-02 10:50
Hello. Problem seems to be back since v1.5.5

**Comment by iou90** [comment] 2021-01-12 06:46
@abenoit-reeliant Can not reproduce it with:
``` json
"react": "16.13.1",
"react-native": "0.63.4",
"react-native-autoheight-webview": "^1.5.7",
"react-native-webview": "^11.0.2"
```

**Comment by abenoit-reeliant** [comment] 2021-01-18 16:44
We were indeed using an older version of react-native-webview. Upgrading to 11.0.2 fixed it. Thanks for the help!

**Closed** 2021-01-19 16:19 UTC
Labels: bug
